#!/usr/bin/env bash
# 安装 shuttle 到 PREFIX，并根据远程 HTTP(S) 地址克隆到本机后写入 linux/.shuttle.env/config
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHUTTLE_TOOL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PREFIX="${PREFIX:-/usr/local}"
LIBDIR="${PREFIX}/lib/shuttle"
BINDIR="${PREFIX}/bin"
CONFIG_DIR="${LIBDIR}/shuttle_tool/linux/.shuttle.env"
CONFIG_PATH="${CONFIG_DIR}/config"
CLONE_BASE="${HOME}/.shuttle/repos"

maybe_sudo=()
if [[ "$(id -u)" != "0" ]] && { [[ "${PREFIX}" == /usr/* ]] || [[ "${PREFIX}" == /opt/* ]]; }; then
  if command -v sudo >/dev/null 2>&1; then
    maybe_sudo=(sudo)
  else
    echo "无法写入 ${PREFIX}，且未找到 sudo。请使用 root 执行，或设置 PREFIX 指向你有写权限的前缀，例如:" >&2
    echo "  PREFIX=\${HOME}/.local bash $0" >&2
    exit 1
  fi
fi

echo "=== shuttle 安装：将克隆远程仓库并写入 ${CONFIG_PATH}（勿提交到 Git）==="
echo ""
read -r -p "Git 仓库 HTTP/HTTPS 地址（必填，例如 https://github.com/org/repo.git；不要填本地路径）: " URL || true
URL="${URL//\"/}"
URL="${URL//\'/}"
URL="${URL#"${URL%%[![:space:]]*}"}"
URL="${URL%"${URL##*[![:space:]]}"}"
if [[ -z "${URL}" ]]; then
  echo "未填写仓库地址，已中止。" >&2
  exit 1
fi
if [[ ! "${URL}" =~ ^https?:// ]]; then
  echo "地址必须以 http:// 或 https:// 开头（不要填本地路径）。" >&2
  exit 1
fi

read -r -p "克隆分支（可选，回车使用远程默认分支）: " CLONE_BRANCH || true
CLONE_BRANCH="${CLONE_BRANCH//\"/}"
CLONE_BRANCH="${CLONE_BRANCH#"${CLONE_BRANCH%%[![:space:]]*}"}"
CLONE_BRANCH="${CLONE_BRANCH%"${CLONE_BRANCH##*[![:space:]]}"}"

read -r -p "SHUTTLE_PAYLOAD_REL（可选，回车使用程序默认）: " PAYLOAD || true
PAYLOAD="${PAYLOAD//\"/}"
PAYLOAD="${PAYLOAD#"${PAYLOAD%%[![:space:]]*}"}"
PAYLOAD="${PAYLOAD%"${PAYLOAD##*[![:space:]]}"}"

read -r -p "SHUTTLE_REMOTE（可选，回车使用 origin）: " REMOTE || true
REMOTE="${REMOTE//\"/}"
REMOTE="${REMOTE#"${REMOTE%%[![:space:]]*}"}"
REMOTE="${REMOTE%"${REMOTE##*[![:space:]]}"}"

read -r -p "SHUTTLE_BRANCH（可选，回车表示使用当前检出分支）: " BRANCH || true
BRANCH="${BRANCH//\"/}"
BRANCH="${BRANCH#"${BRANCH%%[![:space:]]*}"}"
BRANCH="${BRANCH%"${BRANCH##*[![:space:]]}"}"

url_noparam="${URL%%\?*}"
slug="${url_noparam##*/}"
slug="${slug%.git}"
[[ -z "${slug}" ]] && slug="repo"
clone_dir="${CLONE_BASE}/${slug}"

mkdir -p "${CLONE_BASE}"
if [[ -e "${clone_dir}" ]] && [[ ! -d "${clone_dir}/.git" ]]; then
  echo "目标目录已存在且不是 Git 仓库: ${clone_dir}" >&2
  exit 1
fi

if [[ -d "${clone_dir}/.git" ]]; then
  echo "已存在本地克隆，更新 remote 并 pull: ${clone_dir}"
  git -C "${clone_dir}" remote set-url origin "${URL}"
  git -C "${clone_dir}" pull --rebase || true
else
  echo "正在克隆到: ${clone_dir}"
  if [[ -n "${CLONE_BRANCH}" ]]; then
    git clone -b "${CLONE_BRANCH}" "${URL}" "${clone_dir}"
  else
    git clone "${URL}" "${clone_dir}"
  fi
fi

"${maybe_sudo[@]}" mkdir -p "${LIBDIR}" "${BINDIR}"
"${maybe_sudo[@]}" rm -rf "${LIBDIR}/shuttle_tool"
"${maybe_sudo[@]}" cp -a "${SHUTTLE_TOOL_DIR}" "${LIBDIR}/shuttle_tool"
"${maybe_sudo[@]}" rm -rf "${CONFIG_DIR}"
"${maybe_sudo[@]}" mkdir -p "${CONFIG_DIR}"

tmp_cfg="$(mktemp)"
{
  echo "# Generated by shuttle_tool/linux/install.sh — 勿提交到 Git 仓库"
  printf 'SHUTTLE_REPO_ROOT=%q\n' "${clone_dir}"
  printf 'SHUTTLE_REPO_URL=%q\n' "${URL}"
  if [[ -n "${PAYLOAD}" ]]; then
    printf 'SHUTTLE_PAYLOAD_REL=%q\n' "${PAYLOAD}"
  fi
  if [[ -n "${REMOTE}" ]]; then
    printf 'SHUTTLE_REMOTE=%q\n' "${REMOTE}"
  fi
  if [[ -n "${BRANCH}" ]]; then
    printf 'SHUTTLE_BRANCH=%q\n' "${BRANCH}"
  fi
} >"${tmp_cfg}"
"${maybe_sudo[@]}" cp "${tmp_cfg}" "${CONFIG_PATH}"
rm -f "${tmp_cfg}"

"${maybe_sudo[@]}" tee "${BINDIR}/shuttle" >/dev/null <<EOF
#!/usr/bin/env bash
set -e
CONFIG="${CONFIG_PATH}"
if [[ ! -f "\$CONFIG" ]]; then
  echo "缺少配置文件: ${CONFIG_PATH}，请重新运行 shuttle_tool/linux/install.sh。" >&2
  exit 1
fi
set -a
# shellcheck disable=SC1090
source "\$CONFIG"
set +a
export PYTHONPATH="${LIBDIR}\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m shuttle_tool.linux.shuttle_cmd "\$@"
EOF
"${maybe_sudo[@]}" chmod +x "${BINDIR}/shuttle"

echo ""
echo "已安装:"
echo "  启动脚本: ${BINDIR}/shuttle"
echo "  程序库:   ${LIBDIR}/shuttle_tool"
echo "  本地克隆: ${clone_dir}"
echo "  配置文件: ${CONFIG_PATH}"
echo ""
echo "请将 ${BINDIR} 加入 PATH（若尚未加入）。用法: shuttle -h"
