#!/usr/bin/env bash
# 将 shuttle CLI 安装到 PREFIX（默认 /usr/local），并交互生成 ~/.shuttle.info
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHUTTLE_TOOL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PREFIX="${PREFIX:-/usr/local}"
LIBDIR="${PREFIX}/lib/shuttle"
BINDIR="${PREFIX}/bin"
INFO_FILE="${HOME}/.shuttle.info"

maybe_sudo=()
if [[ "$(id -u)" != "0" ]] && { [[ "${PREFIX}" == /usr/* ]] || [[ "${PREFIX}" == /opt/* ]]; }; then
  if command -v sudo >/dev/null 2>&1; then
    maybe_sudo=(sudo)
  else
    echo "无法写入 ${PREFIX}，且未找到 sudo。请使用 root 执行，或设置 PREFIX 指向你有写权限的前缀，例如:" >&2
    echo "  PREFIX=\${HOME}/.local bash $0" >&2
    exit 1
  fi
fi

echo "=== shuttle 安装：环境变量将写入 ${INFO_FILE}（请勿提交到 Git）==="
echo ""
read -r -p "SHUTTLE_REPO_ROOT（必填，本机 Git clone 根目录绝对路径）: " ROOT || true
ROOT="${ROOT//\"/}"
ROOT="${ROOT//\'/}"
ROOT="${ROOT#"${ROOT%%[![:space:]]*}"}"
ROOT="${ROOT%"${ROOT##*[![:space:]]}"}"
if [[ -z "${ROOT}" ]]; then
  echo "未填写 SHUTTLE_REPO_ROOT，已中止。" >&2
  exit 1
fi

read -r -p "SHUTTLE_PAYLOAD_REL（可选，回车使用程序默认 shuttle_tool/shuttle_payload.txt）: " PAYLOAD || true
PAYLOAD="${PAYLOAD//\"/}"
PAYLOAD="${PAYLOAD#"${PAYLOAD%%[![:space:]]*}"}"
PAYLOAD="${PAYLOAD%"${PAYLOAD##*[![:space:]]}"}"

read -r -p "SHUTTLE_REMOTE（可选，回车使用 origin）: " REMOTE || true
REMOTE="${REMOTE//\"/}"
REMOTE="${REMOTE#"${REMOTE%%[![:space:]]*}"}"
REMOTE="${REMOTE%"${REMOTE##*[![:space:]]}"}"

read -r -p "SHUTTLE_BRANCH（可选，回车表示使用当前检出分支）: " BRANCH || true
BRANCH="${BRANCH//\"/}"
BRANCH="${BRANCH#"${BRANCH%%[![:space:]]*}"}"
BRANCH="${BRANCH%"${BRANCH##*[![:space:]]}"}"

{
  echo "# Generated by shuttle_tool/linux/install.sh — 本地配置，勿提交到 Git 仓库"
  printf 'export SHUTTLE_REPO_ROOT=%q\n' "${ROOT}"
  if [[ -n "${PAYLOAD}" ]]; then
    printf 'export SHUTTLE_PAYLOAD_REL=%q\n' "${PAYLOAD}"
  fi
  if [[ -n "${REMOTE}" ]]; then
    printf 'export SHUTTLE_REMOTE=%q\n' "${REMOTE}"
  fi
  if [[ -n "${BRANCH}" ]]; then
    printf 'export SHUTTLE_BRANCH=%q\n' "${BRANCH}"
  fi
} > "${INFO_FILE}"
chmod 600 "${INFO_FILE}" || true

"${maybe_sudo[@]}" mkdir -p "${LIBDIR}" "${BINDIR}"
"${maybe_sudo[@]}" rm -rf "${LIBDIR}/shuttle_tool"
"${maybe_sudo[@]}" cp -a "${SHUTTLE_TOOL_DIR}" "${LIBDIR}/shuttle_tool"

# 生成 shuttle 启动脚本（内嵌 LIBDIR，运行时读取 ~/.shuttle.info）
"${maybe_sudo[@]}" tee "${BINDIR}/shuttle" >/dev/null <<EOF
#!/usr/bin/env bash
set -e
SHUTTLE_INFO="\$HOME/.shuttle.info"
if [[ ! -f "\$SHUTTLE_INFO" ]]; then
  echo "缺少 \$HOME/.shuttle.info，请运行 shuttle_tool/linux/install.sh 进行配置。" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "\$SHUTTLE_INFO"
export PYTHONPATH="${LIBDIR}\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m shuttle_tool.linux.shuttle_cmd "\$@"
EOF
"${maybe_sudo[@]}" chmod +x "${BINDIR}/shuttle"

echo ""
echo "已安装:"
echo "  启动脚本: ${BINDIR}/shuttle"
echo "  程序库:   ${LIBDIR}/shuttle_tool"
echo "  本地配置: ${INFO_FILE}"
echo ""
echo "请将 ${BINDIR} 加入 PATH（若尚未加入）。用法: shuttle -h"
